### ISSUE TITLE
Could you please release the face/body visual feature or the training code for the cast, and the tracklet?

### ISSUE THREAD

**Issue by vana77** [hqqasw/person-search-PPCC#1]
Could you please release the face/body visual feature or the training code for the cast, and the tracklet?
Thanks.

**Comment by hqqasw** [comment]
Thanks for your interest in our work. The feature has been released now. You can download it [here](https://drive.google.com/drive/folders/1YiT2UPRpOXq9KIb4Rnu_Z63METVweHpW?usp=sharing).
