### ISSUE TITLE
test demo？

### ISSUE THREAD

**Issue by Adorablepet** [hqqasw/person-search-PPCC#3]
Sorry to disturb you again, I just ran a bit of code, just a simple result, I would like to ask, is there such a test demo, such as I enter the photo of Andy Lau, and then gamble in the movie to find him Photo?

**Comment by hqqasw** [comment]
Sorry that there is no such demo since it is a just academic repo. But I think you can use the algorithm to implement what you want. Hope it would be helpful.

**Comment by Adorablepet** [comment]
@hqqasw thanks.
