### ISSUE TITLE
If the portraits are unlabeled data , does the algorithm still work?

### ISSUE THREAD

**Issue by wangyongjie-ntu** [hqqasw/person-search-PPCC#4]
@hqqasw  Dear Qingqiu, 

after reading your paper, I have two questions below:

1, If the portraits are unlabeled data, even the gallery set is also unlabeled, Can the algorithm proposed still work? how?

2, If I want to search a portrait doesn't include in the gallery set, how to set the initial probability? should the length of one-hot vector be C+1 ?

**Comment by hqqasw** [comment]
1. The protraits should be labeled. At least you should know its ID (you can labeled them as no.1, no.2, etc.).

2. It can be C+1. You can just labeled the identity of the extened protrait as C+1.
