### ISSUE TITLE
Could you provide face classifier pretrained weight?

### ISSUE THREAD

**Issue by LiuJoffrey** [hqqasw/person-search-PPCC#7]
Hi, 
I would like to train my face feature extractor to reproduce this work, but the download link of the Celeb-1M dataset has been deleted. So could you please provide the pre-trained weight of the face classifier.
Thank you so much

**Comment by hqqasw** [comment]
Plase see this repo: https://github.com/hqqasw/FaceTool
You can download the weights and use the inference code in this repo.
